project:
  type: book
  output-dir: docs

book:
  title: "Métodos Cuantitativos"
  subtitle: "Materiales de cátedra y de consulta" 
  author: "Aleksander Dietrichson, PhD"
  date: "01/15/2023"
  downloads: pdf
  chapters:
    - index.qmd
    - 01-conceptos-fundamentales.qmd
    - 02-distribuciones-de-frecuencias.qmd
    - 03-tendencia-central-y-variabilidad.qmd
    - 04-la-distribucion-normal.qmd
lang: es

bibliography: [book.bib, packages.bib]

crossref:
  chapters: true
  
format:
  html:
    theme: cosmo
    number-sections: true
  pdf:
    documentclass: scrreprt
    toc: true
    # number-sections: false
    colorlinks: true
    include-in-header: 
      text: |
        \usepackage{mdframed}

editor: visual